// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {archive} from '../models';
import {common} from '../models';

export function FindArchivedCourses(arg1:archive.FindArchivedEntryParams,arg2:common.PageParams):Promise<common.Page[fit_and_roll/backend/archive>;

export function FindArchivedParticipants(arg1:archive.FindArchivedEntryParams,arg2:common.PageParams):Promise<common.Page[fit_and_roll/backend/archive>;

export function UnarchiveCourse(arg1:any):Promise<void>;

export function UnarchiveParticipant(arg1:any):Promise<void>;
