// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindArchivedCourses(arg1, arg2) {
  return window['go']['archive']['ArchivedDataHandler']['FindArchivedCourses'](arg1, arg2);
}

export function FindArchivedParticipants(arg1, arg2) {
  return window['go']['archive']['ArchivedDataHandler']['FindArchivedParticipants'](arg1, arg2);
}

export function UnarchiveCourse(arg1) {
  return window['go']['archive']['ArchivedDataHandler']['UnarchiveCourse'](arg1);
}

export function UnarchiveParticipant(arg1) {
  return window['go']['archive']['ArchivedDataHandler']['UnarchiveParticipant'](arg1);
}
