// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportData() {
  return window['go']['archive']['ExportDataHandler']['ExportData']();
}

export function SetContext(arg1) {
  return window['go']['archive']['ExportDataHandler']['SetContext'](arg1);
}
