// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttendCourse(arg1) {
  return window['go']['membercardattendance']['MemberCardAttendanceHandler']['AttendCourse'](arg1);
}

export function FindActiveMemberCards(arg1) {
  return window['go']['membercardattendance']['MemberCardAttendanceHandler']['FindActiveMemberCards'](arg1);
}

export function LoadMemberCardCourseHistory(arg1, arg2) {
  return window['go']['membercardattendance']['MemberCardAttendanceHandler']['LoadMemberCardCourseHistory'](arg1, arg2);
}
