// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {statistics} from '../models';
import {common} from '../models';

export function CourseStatistics(arg1:statistics.StatisticsParams,arg2:common.PageParams):Promise<common.Page[fit_and_roll/backend/statistics>;

export function ParticipantStatistics(arg1:statistics.StatisticsParams,arg2:common.PageParams):Promise<common.Page[fit_and_roll/backend/statistics>;
