// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CourseStatistics(arg1, arg2) {
  return window['go']['statistics']['StatisticsHandler']['CourseStatistics'](arg1, arg2);
}

export function ParticipantStatistics(arg1, arg2) {
  return window['go']['statistics']['StatisticsHandler']['ParticipantStatistics'](arg1, arg2);
}
