// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindAllMemberCards(arg1) {
  return window['go']['participants']['MemberCardController']['FindAllMemberCards'](arg1);
}

export function IssueNewMemberCard(arg1) {
  return window['go']['participants']['MemberCardController']['IssueNewMemberCard'](arg1);
}

export function LoadMemberCardCourseHistory(arg1, arg2) {
  return window['go']['participants']['MemberCardController']['LoadMemberCardCourseHistory'](arg1, arg2);
}

export function UndoIssueNewMemberCard(arg1, arg2) {
  return window['go']['participants']['MemberCardController']['UndoIssueNewMemberCard'](arg1, arg2);
}
