// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttendCourse(arg1) {
  return window['go']['participants']['MemberCardCourseParticipationController']['AttendCourse'](arg1);
}

export function FindActiveMemberCards(arg1) {
  return window['go']['participants']['MemberCardCourseParticipationController']['FindActiveMemberCards'](arg1);
}
