// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {participants} from '../models';

export function FindAllMemberCards(arg1:number):Promise<Array<participants.MemberCardInfo>>;

export function IssueNewMemberCard(arg1:number):Promise<void>;

export function LoadMemberCardCourseHistory(arg1:number,arg2:number):Promise<Array<participants.MemberCardHistoryEntry>>;

export function UndoIssueNewMemberCard(arg1:number,arg2:number):Promise<void>;
