// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {participants} from '../models';

export function FindActiveMemberCards(arg1:number):Promise<Array<participants.MemberCardInfo>>;
