// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {participants} from '../models';
import {common} from '../models';

export function ArchiveParticipant(arg1:number):Promise<void>;

export function CreateUpdateParticipant(arg1:participants.ParticipantCommand):Promise<void>;

export function FindParticipantDetails(arg1:number):Promise<participants.ParticipantDto>;

export function FindParticipants(arg1:participants.FindParticipantsParams,arg2:common.PageParams):Promise<common.Page[fit_and_roll/backend/participants>;
