// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveParticipant(arg1) {
  return window['go']['participants']['ParticipantsHandler']['ArchiveParticipant'](arg1);
}

export function CreateUpdateParticipant(arg1) {
  return window['go']['participants']['ParticipantsHandler']['CreateUpdateParticipant'](arg1);
}

export function FindParticipantDetails(arg1) {
  return window['go']['participants']['ParticipantsHandler']['FindParticipantDetails'](arg1);
}

export function FindParticipants(arg1, arg2) {
  return window['go']['participants']['ParticipantsHandler']['FindParticipants'](arg1, arg2);
}
