// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchRootFontSize():Promise<number>;

export function PersistRootFontSize(arg1:number):Promise<void>;
