// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchRootFontSize() {
  return window['go']['scaler']['ScalerHandler']['FetchRootFontSize']();
}

export function PersistRootFontSize(arg1) {
  return window['go']['scaler']['ScalerHandler']['PersistRootFontSize'](arg1);
}
