// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {courseattendance} from '../models';
import {common} from '../models';

export function FindCourseAttendanceHistory(arg1:courseattendance.CourseAttendanceParameters,arg2:common.PageParams):Promise<common.Page[fit_and_roll/backend/courseattendance>;
