// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {courseattendance} from '../models';

export function FindOverallAttendanceHistory():Promise<Array<courseattendance.CourseAttendanceDto>>;
