// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindCourseAttendanceHistory(arg1, arg2) {
  return window['go']['courseattendance']['CourseAttendanceHandler']['FindCourseAttendanceHistory'](arg1, arg2);
}

export function UndoCourseAttendance(arg1) {
  return window['go']['courseattendance']['CourseAttendanceHandler']['UndoCourseAttendance'](arg1);
}
