// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportParticipants() {
  return window['go']['import_']['ImportParticipantsHandler']['ImportParticipants']();
}

export function SetContext(arg1) {
  return window['go']['import_']['ImportParticipantsHandler']['SetContext'](arg1);
}
