// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {courses} from '../models';
import {common} from '../models';

export function ArchiveCourse(arg1:number):Promise<void>;

export function FindCourseDetails(arg1:number):Promise<courses.Course>;

export function FindCourses(arg1:number,arg2:number):Promise<common.Page[fit_and_roll/backend/courses>;

export function NewCourse(arg1:courses.CourseRequest):Promise<void>;

export function UpdateCourse(arg1:number,arg2:courses.CourseRequest):Promise<void>;
