// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveCourse(arg1) {
  return window['go']['courses']['CourseController']['ArchiveCourse'](arg1);
}

export function FindCourseDetails(arg1) {
  return window['go']['courses']['CourseController']['FindCourseDetails'](arg1);
}

export function FindCourses(arg1, arg2) {
  return window['go']['courses']['CourseController']['FindCourses'](arg1, arg2);
}

export function NewCourse(arg1) {
  return window['go']['courses']['CourseController']['NewCourse'](arg1);
}

export function UpdateCourse(arg1) {
  return window['go']['courses']['CourseController']['UpdateCourse'](arg1);
}
